namespace CapaPresentacion
{
    partial class frmReportes
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(frmReportes));
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle1 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle2 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle3 = new System.Windows.Forms.DataGridViewCellStyle();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges5 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            this.bunifuLabel1 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel3 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuDataGridView1 = new Bunifu.UI.WinForms.BunifuDataGridView();
            this.categoriaGanancias = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.Compras = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.Ventas = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.btnStock = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.gananciasVendedor = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            ((System.ComponentModel.ISupportInitialize)(this.bunifuDataGridView1)).BeginInit();
            this.SuspendLayout();
            // 
            // bunifuLabel1
            // 
            this.bunifuLabel1.AllowParentOverrides = false;
            this.bunifuLabel1.AutoEllipsis = false;
            this.bunifuLabel1.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.Font = new System.Drawing.Font("Century Gothic", 36F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel1.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(39)))), ((int)(((byte)(40)))));
            this.bunifuLabel1.Location = new System.Drawing.Point(347, 12);
            this.bunifuLabel1.Name = "bunifuLabel1";
            this.bunifuLabel1.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel1.Size = new System.Drawing.Size(203, 56);
            this.bunifuLabel1.TabIndex = 37;
            this.bunifuLabel1.Text = "Reportes";
            this.bunifuLabel1.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel1.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel3
            // 
            this.bunifuLabel3.AllowParentOverrides = false;
            this.bunifuLabel3.AutoEllipsis = false;
            this.bunifuLabel3.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel3.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel3.Font = new System.Drawing.Font("Century Gothic", 26.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel3.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(178)))), ((int)(((byte)(8)))), ((int)(((byte)(55)))));
            this.bunifuLabel3.Location = new System.Drawing.Point(250, 74);
            this.bunifuLabel3.Name = "bunifuLabel3";
            this.bunifuLabel3.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel3.Size = new System.Drawing.Size(382, 39);
            this.bunifuLabel3.TabIndex = 40;
            this.bunifuLabel3.Text = "Obtener reportes sobre:";
            this.bunifuLabel3.TextAlignment = System.Drawing.ContentAlignment.TopCenter;
            this.bunifuLabel3.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuDataGridView1
            // 
            this.bunifuDataGridView1.AllowCustomTheming = false;
            dataGridViewCellStyle1.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(223)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            dataGridViewCellStyle1.ForeColor = System.Drawing.Color.Black;
            this.bunifuDataGridView1.AlternatingRowsDefaultCellStyle = dataGridViewCellStyle1;
            this.bunifuDataGridView1.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this.bunifuDataGridView1.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.bunifuDataGridView1.CellBorderStyle = System.Windows.Forms.DataGridViewCellBorderStyle.SingleHorizontal;
            this.bunifuDataGridView1.ColumnHeadersBorderStyle = System.Windows.Forms.DataGridViewHeaderBorderStyle.None;
            dataGridViewCellStyle2.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle2.BackColor = System.Drawing.Color.Maroon;
            dataGridViewCellStyle2.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle2.ForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle2.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(102)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            dataGridViewCellStyle2.SelectionForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle2.WrapMode = System.Windows.Forms.DataGridViewTriState.True;
            this.bunifuDataGridView1.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle2;
            this.bunifuDataGridView1.ColumnHeadersHeight = 40;
            this.bunifuDataGridView1.CurrentTheme.AlternatingRowsStyle.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(223)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuDataGridView1.CurrentTheme.AlternatingRowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.bunifuDataGridView1.CurrentTheme.AlternatingRowsStyle.ForeColor = System.Drawing.Color.Black;
            this.bunifuDataGridView1.CurrentTheme.AlternatingRowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(178)))), ((int)(((byte)(102)))), ((int)(((byte)(102)))));
            this.bunifuDataGridView1.CurrentTheme.AlternatingRowsStyle.SelectionForeColor = System.Drawing.Color.White;
            this.bunifuDataGridView1.CurrentTheme.BackColor = System.Drawing.Color.Maroon;
            this.bunifuDataGridView1.CurrentTheme.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(216)))), ((int)(((byte)(178)))), ((int)(((byte)(178)))));
            this.bunifuDataGridView1.CurrentTheme.HeaderStyle.BackColor = System.Drawing.Color.Maroon;
            this.bunifuDataGridView1.CurrentTheme.HeaderStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            this.bunifuDataGridView1.CurrentTheme.HeaderStyle.ForeColor = System.Drawing.Color.White;
            this.bunifuDataGridView1.CurrentTheme.HeaderStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(102)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.bunifuDataGridView1.CurrentTheme.HeaderStyle.SelectionForeColor = System.Drawing.Color.White;
            this.bunifuDataGridView1.CurrentTheme.Name = null;
            this.bunifuDataGridView1.CurrentTheme.RowsStyle.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(229)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuDataGridView1.CurrentTheme.RowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.bunifuDataGridView1.CurrentTheme.RowsStyle.ForeColor = System.Drawing.Color.Black;
            this.bunifuDataGridView1.CurrentTheme.RowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(178)))), ((int)(((byte)(102)))), ((int)(((byte)(102)))));
            this.bunifuDataGridView1.CurrentTheme.RowsStyle.SelectionForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle3.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle3.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(229)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            dataGridViewCellStyle3.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle3.ForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle3.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(178)))), ((int)(((byte)(102)))), ((int)(((byte)(102)))));
            dataGridViewCellStyle3.SelectionForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle3.WrapMode = System.Windows.Forms.DataGridViewTriState.False;
            this.bunifuDataGridView1.DefaultCellStyle = dataGridViewCellStyle3;
            this.bunifuDataGridView1.Dock = System.Windows.Forms.DockStyle.Bottom;
            this.bunifuDataGridView1.EnableHeadersVisualStyles = false;
            this.bunifuDataGridView1.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(216)))), ((int)(((byte)(178)))), ((int)(((byte)(178)))));
            this.bunifuDataGridView1.HeaderBackColor = System.Drawing.Color.Maroon;
            this.bunifuDataGridView1.HeaderBgColor = System.Drawing.Color.Empty;
            this.bunifuDataGridView1.HeaderForeColor = System.Drawing.Color.White;
            this.bunifuDataGridView1.Location = new System.Drawing.Point(0, 497);
            this.bunifuDataGridView1.Name = "bunifuDataGridView1";
            this.bunifuDataGridView1.RowHeadersVisible = false;
            this.bunifuDataGridView1.RowTemplate.Height = 40;
            this.bunifuDataGridView1.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.bunifuDataGridView1.Size = new System.Drawing.Size(889, 28);
            this.bunifuDataGridView1.TabIndex = 42;
            this.bunifuDataGridView1.Theme = Bunifu.UI.WinForms.BunifuDataGridView.PresetThemes.Maroon;
            // 
            // categoriaGanancias
            // 
            this.categoriaGanancias.AllowAnimations = true;
            this.categoriaGanancias.AllowMouseEffects = true;
            this.categoriaGanancias.AllowToggling = false;
            this.categoriaGanancias.AnimationSpeed = 200;
            this.categoriaGanancias.AutoGenerateColors = false;
            this.categoriaGanancias.AutoRoundBorders = true;
            this.categoriaGanancias.AutoSizeLeftIcon = true;
            this.categoriaGanancias.AutoSizeRightIcon = true;
            this.categoriaGanancias.BackColor = System.Drawing.Color.Transparent;
            this.categoriaGanancias.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.categoriaGanancias.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("categoriaGanancias.BackgroundImage")));
            this.categoriaGanancias.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.categoriaGanancias.ButtonText = "Ganancias por Categorias";
            this.categoriaGanancias.ButtonTextMarginLeft = 0;
            this.categoriaGanancias.ColorContrastOnClick = 45;
            this.categoriaGanancias.ColorContrastOnHover = 45;
            this.categoriaGanancias.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.categoriaGanancias.CustomizableEdges = borderEdges1;
            this.categoriaGanancias.DialogResult = System.Windows.Forms.DialogResult.None;
            this.categoriaGanancias.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.categoriaGanancias.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.categoriaGanancias.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.categoriaGanancias.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.categoriaGanancias.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.categoriaGanancias.ForeColor = System.Drawing.Color.White;
            this.categoriaGanancias.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.categoriaGanancias.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.categoriaGanancias.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.categoriaGanancias.IconMarginLeft = 11;
            this.categoriaGanancias.IconPadding = 10;
            this.categoriaGanancias.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.categoriaGanancias.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.categoriaGanancias.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.categoriaGanancias.IconSize = 25;
            this.categoriaGanancias.IdleBorderColor = System.Drawing.Color.Black;
            this.categoriaGanancias.IdleBorderRadius = 37;
            this.categoriaGanancias.IdleBorderThickness = 1;
            this.categoriaGanancias.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.categoriaGanancias.IdleIconLeftImage = null;
            this.categoriaGanancias.IdleIconRightImage = null;
            this.categoriaGanancias.IndicateFocus = false;
            this.categoriaGanancias.Location = new System.Drawing.Point(519, 380);
            this.categoriaGanancias.Name = "categoriaGanancias";
            this.categoriaGanancias.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.categoriaGanancias.OnDisabledState.BorderRadius = 1;
            this.categoriaGanancias.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.categoriaGanancias.OnDisabledState.BorderThickness = 1;
            this.categoriaGanancias.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.categoriaGanancias.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.categoriaGanancias.OnDisabledState.IconLeftImage = null;
            this.categoriaGanancias.OnDisabledState.IconRightImage = null;
            this.categoriaGanancias.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.categoriaGanancias.onHoverState.BorderRadius = 1;
            this.categoriaGanancias.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.categoriaGanancias.onHoverState.BorderThickness = 1;
            this.categoriaGanancias.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.categoriaGanancias.onHoverState.ForeColor = System.Drawing.Color.White;
            this.categoriaGanancias.onHoverState.IconLeftImage = null;
            this.categoriaGanancias.onHoverState.IconRightImage = null;
            this.categoriaGanancias.OnIdleState.BorderColor = System.Drawing.Color.Black;
            this.categoriaGanancias.OnIdleState.BorderRadius = 1;
            this.categoriaGanancias.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.categoriaGanancias.OnIdleState.BorderThickness = 1;
            this.categoriaGanancias.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.categoriaGanancias.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.categoriaGanancias.OnIdleState.IconLeftImage = null;
            this.categoriaGanancias.OnIdleState.IconRightImage = null;
            this.categoriaGanancias.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.categoriaGanancias.OnPressedState.BorderRadius = 1;
            this.categoriaGanancias.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.categoriaGanancias.OnPressedState.BorderThickness = 1;
            this.categoriaGanancias.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.categoriaGanancias.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.categoriaGanancias.OnPressedState.IconLeftImage = null;
            this.categoriaGanancias.OnPressedState.IconRightImage = null;
            this.categoriaGanancias.Size = new System.Drawing.Size(150, 39);
            this.categoriaGanancias.TabIndex = 43;
            this.categoriaGanancias.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.categoriaGanancias.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.categoriaGanancias.TextMarginLeft = 0;
            this.categoriaGanancias.TextPadding = new System.Windows.Forms.Padding(0);
            this.categoriaGanancias.UseDefaultRadiusAndThickness = true;
            this.categoriaGanancias.Click += new System.EventHandler(this.categoriaGanancias_Click);
            // 
            // Compras
            // 
            this.Compras.AllowAnimations = true;
            this.Compras.AllowMouseEffects = true;
            this.Compras.AllowToggling = false;
            this.Compras.AnimationSpeed = 200;
            this.Compras.AutoGenerateColors = false;
            this.Compras.AutoRoundBorders = true;
            this.Compras.AutoSizeLeftIcon = true;
            this.Compras.AutoSizeRightIcon = true;
            this.Compras.BackColor = System.Drawing.Color.Transparent;
            this.Compras.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.Compras.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("Compras.BackgroundImage")));
            this.Compras.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.Compras.ButtonText = "Compras";
            this.Compras.ButtonTextMarginLeft = 0;
            this.Compras.ColorContrastOnClick = 45;
            this.Compras.ColorContrastOnHover = 45;
            this.Compras.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.Compras.CustomizableEdges = borderEdges2;
            this.Compras.DialogResult = System.Windows.Forms.DialogResult.None;
            this.Compras.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.Compras.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.Compras.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.Compras.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.Compras.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.Compras.ForeColor = System.Drawing.Color.White;
            this.Compras.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.Compras.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.Compras.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.Compras.IconMarginLeft = 11;
            this.Compras.IconPadding = 10;
            this.Compras.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.Compras.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.Compras.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.Compras.IconSize = 25;
            this.Compras.IdleBorderColor = System.Drawing.Color.Black;
            this.Compras.IdleBorderRadius = 37;
            this.Compras.IdleBorderThickness = 1;
            this.Compras.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.Compras.IdleIconLeftImage = null;
            this.Compras.IdleIconRightImage = null;
            this.Compras.IndicateFocus = false;
            this.Compras.Location = new System.Drawing.Point(363, 213);
            this.Compras.Name = "Compras";
            this.Compras.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.Compras.OnDisabledState.BorderRadius = 1;
            this.Compras.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.Compras.OnDisabledState.BorderThickness = 1;
            this.Compras.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.Compras.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.Compras.OnDisabledState.IconLeftImage = null;
            this.Compras.OnDisabledState.IconRightImage = null;
            this.Compras.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.Compras.onHoverState.BorderRadius = 1;
            this.Compras.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.Compras.onHoverState.BorderThickness = 1;
            this.Compras.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.Compras.onHoverState.ForeColor = System.Drawing.Color.White;
            this.Compras.onHoverState.IconLeftImage = null;
            this.Compras.onHoverState.IconRightImage = null;
            this.Compras.OnIdleState.BorderColor = System.Drawing.Color.Black;
            this.Compras.OnIdleState.BorderRadius = 1;
            this.Compras.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.Compras.OnIdleState.BorderThickness = 1;
            this.Compras.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.Compras.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.Compras.OnIdleState.IconLeftImage = null;
            this.Compras.OnIdleState.IconRightImage = null;
            this.Compras.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.Compras.OnPressedState.BorderRadius = 1;
            this.Compras.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.Compras.OnPressedState.BorderThickness = 1;
            this.Compras.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.Compras.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.Compras.OnPressedState.IconLeftImage = null;
            this.Compras.OnPressedState.IconRightImage = null;
            this.Compras.Size = new System.Drawing.Size(150, 39);
            this.Compras.TabIndex = 44;
            this.Compras.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.Compras.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.Compras.TextMarginLeft = 0;
            this.Compras.TextPadding = new System.Windows.Forms.Padding(0);
            this.Compras.UseDefaultRadiusAndThickness = true;
            this.Compras.Click += new System.EventHandler(this.bunifuButton22_Click);
            // 
            // Ventas
            // 
            this.Ventas.AllowAnimations = true;
            this.Ventas.AllowMouseEffects = true;
            this.Ventas.AllowToggling = false;
            this.Ventas.AnimationSpeed = 200;
            this.Ventas.AutoGenerateColors = false;
            this.Ventas.AutoRoundBorders = true;
            this.Ventas.AutoSizeLeftIcon = true;
            this.Ventas.AutoSizeRightIcon = true;
            this.Ventas.BackColor = System.Drawing.Color.Transparent;
            this.Ventas.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.Ventas.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("Ventas.BackgroundImage")));
            this.Ventas.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.Ventas.ButtonText = "Ventas";
            this.Ventas.ButtonTextMarginLeft = 0;
            this.Ventas.ColorContrastOnClick = 45;
            this.Ventas.ColorContrastOnHover = 45;
            this.Ventas.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.Ventas.CustomizableEdges = borderEdges3;
            this.Ventas.DialogResult = System.Windows.Forms.DialogResult.None;
            this.Ventas.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.Ventas.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.Ventas.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.Ventas.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.Ventas.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.Ventas.ForeColor = System.Drawing.Color.White;
            this.Ventas.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.Ventas.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.Ventas.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.Ventas.IconMarginLeft = 11;
            this.Ventas.IconPadding = 10;
            this.Ventas.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.Ventas.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.Ventas.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.Ventas.IconSize = 25;
            this.Ventas.IdleBorderColor = System.Drawing.Color.Black;
            this.Ventas.IdleBorderRadius = 37;
            this.Ventas.IdleBorderThickness = 1;
            this.Ventas.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.Ventas.IdleIconLeftImage = null;
            this.Ventas.IdleIconRightImage = null;
            this.Ventas.IndicateFocus = false;
            this.Ventas.Location = new System.Drawing.Point(213, 380);
            this.Ventas.Name = "Ventas";
            this.Ventas.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.Ventas.OnDisabledState.BorderRadius = 1;
            this.Ventas.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.Ventas.OnDisabledState.BorderThickness = 1;
            this.Ventas.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.Ventas.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.Ventas.OnDisabledState.IconLeftImage = null;
            this.Ventas.OnDisabledState.IconRightImage = null;
            this.Ventas.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.Ventas.onHoverState.BorderRadius = 1;
            this.Ventas.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.Ventas.onHoverState.BorderThickness = 1;
            this.Ventas.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.Ventas.onHoverState.ForeColor = System.Drawing.Color.White;
            this.Ventas.onHoverState.IconLeftImage = null;
            this.Ventas.onHoverState.IconRightImage = null;
            this.Ventas.OnIdleState.BorderColor = System.Drawing.Color.Black;
            this.Ventas.OnIdleState.BorderRadius = 1;
            this.Ventas.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.Ventas.OnIdleState.BorderThickness = 1;
            this.Ventas.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.Ventas.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.Ventas.OnIdleState.IconLeftImage = null;
            this.Ventas.OnIdleState.IconRightImage = null;
            this.Ventas.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.Ventas.OnPressedState.BorderRadius = 1;
            this.Ventas.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.Ventas.OnPressedState.BorderThickness = 1;
            this.Ventas.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.Ventas.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.Ventas.OnPressedState.IconLeftImage = null;
            this.Ventas.OnPressedState.IconRightImage = null;
            this.Ventas.Size = new System.Drawing.Size(150, 39);
            this.Ventas.TabIndex = 45;
            this.Ventas.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.Ventas.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.Ventas.TextMarginLeft = 0;
            this.Ventas.TextPadding = new System.Windows.Forms.Padding(0);
            this.Ventas.UseDefaultRadiusAndThickness = true;
            this.Ventas.Click += new System.EventHandler(this.Ventas_Click);
            // 
            // btnStock
            // 
            this.btnStock.AllowAnimations = true;
            this.btnStock.AllowMouseEffects = true;
            this.btnStock.AllowToggling = false;
            this.btnStock.AnimationSpeed = 200;
            this.btnStock.AutoGenerateColors = false;
            this.btnStock.AutoRoundBorders = true;
            this.btnStock.AutoSizeLeftIcon = true;
            this.btnStock.AutoSizeRightIcon = true;
            this.btnStock.BackColor = System.Drawing.Color.Transparent;
            this.btnStock.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.btnStock.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnStock.BackgroundImage")));
            this.btnStock.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnStock.ButtonText = "Stock";
            this.btnStock.ButtonTextMarginLeft = 0;
            this.btnStock.ColorContrastOnClick = 45;
            this.btnStock.ColorContrastOnHover = 45;
            this.btnStock.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            this.btnStock.CustomizableEdges = borderEdges4;
            this.btnStock.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnStock.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnStock.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnStock.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnStock.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.btnStock.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.btnStock.ForeColor = System.Drawing.Color.White;
            this.btnStock.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnStock.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.btnStock.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnStock.IconMarginLeft = 11;
            this.btnStock.IconPadding = 10;
            this.btnStock.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnStock.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.btnStock.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnStock.IconSize = 25;
            this.btnStock.IdleBorderColor = System.Drawing.Color.Black;
            this.btnStock.IdleBorderRadius = 37;
            this.btnStock.IdleBorderThickness = 1;
            this.btnStock.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.btnStock.IdleIconLeftImage = null;
            this.btnStock.IdleIconRightImage = null;
            this.btnStock.IndicateFocus = false;
            this.btnStock.Location = new System.Drawing.Point(363, 300);
            this.btnStock.Name = "btnStock";
            this.btnStock.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnStock.OnDisabledState.BorderRadius = 1;
            this.btnStock.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnStock.OnDisabledState.BorderThickness = 1;
            this.btnStock.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnStock.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnStock.OnDisabledState.IconLeftImage = null;
            this.btnStock.OnDisabledState.IconRightImage = null;
            this.btnStock.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnStock.onHoverState.BorderRadius = 1;
            this.btnStock.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnStock.onHoverState.BorderThickness = 1;
            this.btnStock.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnStock.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnStock.onHoverState.IconLeftImage = null;
            this.btnStock.onHoverState.IconRightImage = null;
            this.btnStock.OnIdleState.BorderColor = System.Drawing.Color.Black;
            this.btnStock.OnIdleState.BorderRadius = 1;
            this.btnStock.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnStock.OnIdleState.BorderThickness = 1;
            this.btnStock.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.btnStock.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnStock.OnIdleState.IconLeftImage = null;
            this.btnStock.OnIdleState.IconRightImage = null;
            this.btnStock.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnStock.OnPressedState.BorderRadius = 1;
            this.btnStock.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnStock.OnPressedState.BorderThickness = 1;
            this.btnStock.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnStock.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnStock.OnPressedState.IconLeftImage = null;
            this.btnStock.OnPressedState.IconRightImage = null;
            this.btnStock.Size = new System.Drawing.Size(150, 39);
            this.btnStock.TabIndex = 46;
            this.btnStock.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnStock.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnStock.TextMarginLeft = 0;
            this.btnStock.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnStock.UseDefaultRadiusAndThickness = true;
            this.btnStock.Click += new System.EventHandler(this.btnStock_Click);
            // 
            // gananciasVendedor
            // 
            this.gananciasVendedor.AllowAnimations = true;
            this.gananciasVendedor.AllowMouseEffects = true;
            this.gananciasVendedor.AllowToggling = false;
            this.gananciasVendedor.AnimationSpeed = 200;
            this.gananciasVendedor.AutoGenerateColors = false;
            this.gananciasVendedor.AutoRoundBorders = true;
            this.gananciasVendedor.AutoSizeLeftIcon = true;
            this.gananciasVendedor.AutoSizeRightIcon = true;
            this.gananciasVendedor.BackColor = System.Drawing.Color.Transparent;
            this.gananciasVendedor.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.gananciasVendedor.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("gananciasVendedor.BackgroundImage")));
            this.gananciasVendedor.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.gananciasVendedor.ButtonText = "Ganancias por Vendedor";
            this.gananciasVendedor.ButtonTextMarginLeft = 0;
            this.gananciasVendedor.ColorContrastOnClick = 45;
            this.gananciasVendedor.ColorContrastOnHover = 45;
            this.gananciasVendedor.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges5.BottomLeft = true;
            borderEdges5.BottomRight = true;
            borderEdges5.TopLeft = true;
            borderEdges5.TopRight = true;
            this.gananciasVendedor.CustomizableEdges = borderEdges5;
            this.gananciasVendedor.DialogResult = System.Windows.Forms.DialogResult.None;
            this.gananciasVendedor.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.gananciasVendedor.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.gananciasVendedor.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.gananciasVendedor.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.gananciasVendedor.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.gananciasVendedor.ForeColor = System.Drawing.Color.White;
            this.gananciasVendedor.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.gananciasVendedor.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.gananciasVendedor.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.gananciasVendedor.IconMarginLeft = 11;
            this.gananciasVendedor.IconPadding = 10;
            this.gananciasVendedor.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.gananciasVendedor.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.gananciasVendedor.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.gananciasVendedor.IconSize = 25;
            this.gananciasVendedor.IdleBorderColor = System.Drawing.Color.Black;
            this.gananciasVendedor.IdleBorderRadius = 37;
            this.gananciasVendedor.IdleBorderThickness = 1;
            this.gananciasVendedor.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.gananciasVendedor.IdleIconLeftImage = null;
            this.gananciasVendedor.IdleIconRightImage = null;
            this.gananciasVendedor.IndicateFocus = false;
            this.gananciasVendedor.Location = new System.Drawing.Point(712, 380);
            this.gananciasVendedor.Name = "gananciasVendedor";
            this.gananciasVendedor.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.gananciasVendedor.OnDisabledState.BorderRadius = 1;
            this.gananciasVendedor.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.gananciasVendedor.OnDisabledState.BorderThickness = 1;
            this.gananciasVendedor.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.gananciasVendedor.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.gananciasVendedor.OnDisabledState.IconLeftImage = null;
            this.gananciasVendedor.OnDisabledState.IconRightImage = null;
            this.gananciasVendedor.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.gananciasVendedor.onHoverState.BorderRadius = 1;
            this.gananciasVendedor.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.gananciasVendedor.onHoverState.BorderThickness = 1;
            this.gananciasVendedor.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.gananciasVendedor.onHoverState.ForeColor = System.Drawing.Color.White;
            this.gananciasVendedor.onHoverState.IconLeftImage = null;
            this.gananciasVendedor.onHoverState.IconRightImage = null;
            this.gananciasVendedor.OnIdleState.BorderColor = System.Drawing.Color.Black;
            this.gananciasVendedor.OnIdleState.BorderRadius = 1;
            this.gananciasVendedor.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.gananciasVendedor.OnIdleState.BorderThickness = 1;
            this.gananciasVendedor.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.gananciasVendedor.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.gananciasVendedor.OnIdleState.IconLeftImage = null;
            this.gananciasVendedor.OnIdleState.IconRightImage = null;
            this.gananciasVendedor.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.gananciasVendedor.OnPressedState.BorderRadius = 1;
            this.gananciasVendedor.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.gananciasVendedor.OnPressedState.BorderThickness = 1;
            this.gananciasVendedor.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.gananciasVendedor.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.gananciasVendedor.OnPressedState.IconLeftImage = null;
            this.gananciasVendedor.OnPressedState.IconRightImage = null;
            this.gananciasVendedor.Size = new System.Drawing.Size(150, 39);
            this.gananciasVendedor.TabIndex = 47;
            this.gananciasVendedor.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.gananciasVendedor.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.gananciasVendedor.TextMarginLeft = 0;
            this.gananciasVendedor.TextPadding = new System.Windows.Forms.Padding(0);
            this.gananciasVendedor.UseDefaultRadiusAndThickness = true;
            this.gananciasVendedor.Click += new System.EventHandler(this.gananciasVendedor_Click);
            // 
            // frmReportes
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(889, 525);
            this.Controls.Add(this.gananciasVendedor);
            this.Controls.Add(this.btnStock);
            this.Controls.Add(this.Ventas);
            this.Controls.Add(this.Compras);
            this.Controls.Add(this.categoriaGanancias);
            this.Controls.Add(this.bunifuDataGridView1);
            this.Controls.Add(this.bunifuLabel3);
            this.Controls.Add(this.bunifuLabel1);
            this.Name = "frmReportes";
            this.Text = "frmReportes";
            ((System.ComponentModel.ISupportInitialize)(this.bunifuDataGridView1)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel1;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel3;
        private Bunifu.UI.WinForms.BunifuDataGridView bunifuDataGridView1;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 categoriaGanancias;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 Compras;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 Ventas;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 btnStock;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 gananciasVendedor;
    }
}