namespace CapaPresentacion
{
    partial class frmReportes
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(frmReportes));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges5 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges6 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges7 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges8 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges9 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            this.bunifuLabel1 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel3 = new Bunifu.UI.WinForms.BunifuLabel();
            this.categoriaGanancias = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.Compras = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.Ventas = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.btnStock = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.gananciasVendedor = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.bunifuButton21 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.btnProductoMasVendido = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.bunifuButton22 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.ResumenFinanciero = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.SuspendLayout();
            // 
            // bunifuLabel1
            // 
            this.bunifuLabel1.AllowParentOverrides = false;
            this.bunifuLabel1.AutoEllipsis = false;
            this.bunifuLabel1.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.Font = new System.Drawing.Font("Century Gothic", 36F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel1.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(39)))), ((int)(((byte)(40)))));
            this.bunifuLabel1.Location = new System.Drawing.Point(347, 12);
            this.bunifuLabel1.Name = "bunifuLabel1";
            this.bunifuLabel1.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel1.Size = new System.Drawing.Size(203, 56);
            this.bunifuLabel1.TabIndex = 37;
            this.bunifuLabel1.Text = "Reportes";
            this.bunifuLabel1.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel1.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel3
            // 
            this.bunifuLabel3.AllowParentOverrides = false;
            this.bunifuLabel3.AutoEllipsis = false;
            this.bunifuLabel3.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel3.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel3.Font = new System.Drawing.Font("Century Gothic", 26.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel3.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(178)))), ((int)(((byte)(8)))), ((int)(((byte)(55)))));
            this.bunifuLabel3.Location = new System.Drawing.Point(250, 74);
            this.bunifuLabel3.Name = "bunifuLabel3";
            this.bunifuLabel3.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel3.Size = new System.Drawing.Size(382, 39);
            this.bunifuLabel3.TabIndex = 40;
            this.bunifuLabel3.Text = "Obtener reportes sobre:";
            this.bunifuLabel3.TextAlignment = System.Drawing.ContentAlignment.TopCenter;
            this.bunifuLabel3.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // categoriaGanancias
            // 
            this.categoriaGanancias.AllowAnimations = true;
            this.categoriaGanancias.AllowMouseEffects = true;
            this.categoriaGanancias.AllowToggling = false;
            this.categoriaGanancias.AnimationSpeed = 200;
            this.categoriaGanancias.AutoGenerateColors = false;
            this.categoriaGanancias.AutoRoundBorders = true;
            this.categoriaGanancias.AutoSizeLeftIcon = true;
            this.categoriaGanancias.AutoSizeRightIcon = true;
            this.categoriaGanancias.BackColor = System.Drawing.Color.Transparent;
            this.categoriaGanancias.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.categoriaGanancias.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("categoriaGanancias.BackgroundImage")));
            this.categoriaGanancias.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.categoriaGanancias.ButtonText = "Ganancias por Categorias";
            this.categoriaGanancias.ButtonTextMarginLeft = 0;
            this.categoriaGanancias.ColorContrastOnClick = 45;
            this.categoriaGanancias.ColorContrastOnHover = 45;
            this.categoriaGanancias.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.categoriaGanancias.CustomizableEdges = borderEdges1;
            this.categoriaGanancias.DialogResult = System.Windows.Forms.DialogResult.None;
            this.categoriaGanancias.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.categoriaGanancias.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.categoriaGanancias.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.categoriaGanancias.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.categoriaGanancias.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.categoriaGanancias.ForeColor = System.Drawing.Color.White;
            this.categoriaGanancias.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.categoriaGanancias.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.categoriaGanancias.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.categoriaGanancias.IconMarginLeft = 11;
            this.categoriaGanancias.IconPadding = 10;
            this.categoriaGanancias.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.categoriaGanancias.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.categoriaGanancias.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.categoriaGanancias.IconSize = 25;
            this.categoriaGanancias.IdleBorderColor = System.Drawing.Color.Black;
            this.categoriaGanancias.IdleBorderRadius = 37;
            this.categoriaGanancias.IdleBorderThickness = 1;
            this.categoriaGanancias.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.categoriaGanancias.IdleIconLeftImage = null;
            this.categoriaGanancias.IdleIconRightImage = null;
            this.categoriaGanancias.IndicateFocus = false;
            this.categoriaGanancias.Location = new System.Drawing.Point(117, 170);
            this.categoriaGanancias.Name = "categoriaGanancias";
            this.categoriaGanancias.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.categoriaGanancias.OnDisabledState.BorderRadius = 1;
            this.categoriaGanancias.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.categoriaGanancias.OnDisabledState.BorderThickness = 1;
            this.categoriaGanancias.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.categoriaGanancias.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.categoriaGanancias.OnDisabledState.IconLeftImage = null;
            this.categoriaGanancias.OnDisabledState.IconRightImage = null;
            this.categoriaGanancias.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.categoriaGanancias.onHoverState.BorderRadius = 1;
            this.categoriaGanancias.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.categoriaGanancias.onHoverState.BorderThickness = 1;
            this.categoriaGanancias.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.categoriaGanancias.onHoverState.ForeColor = System.Drawing.Color.White;
            this.categoriaGanancias.onHoverState.IconLeftImage = null;
            this.categoriaGanancias.onHoverState.IconRightImage = null;
            this.categoriaGanancias.OnIdleState.BorderColor = System.Drawing.Color.Black;
            this.categoriaGanancias.OnIdleState.BorderRadius = 1;
            this.categoriaGanancias.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.categoriaGanancias.OnIdleState.BorderThickness = 1;
            this.categoriaGanancias.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.categoriaGanancias.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.categoriaGanancias.OnIdleState.IconLeftImage = null;
            this.categoriaGanancias.OnIdleState.IconRightImage = null;
            this.categoriaGanancias.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.categoriaGanancias.OnPressedState.BorderRadius = 1;
            this.categoriaGanancias.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.categoriaGanancias.OnPressedState.BorderThickness = 1;
            this.categoriaGanancias.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.categoriaGanancias.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.categoriaGanancias.OnPressedState.IconLeftImage = null;
            this.categoriaGanancias.OnPressedState.IconRightImage = null;
            this.categoriaGanancias.Size = new System.Drawing.Size(150, 39);
            this.categoriaGanancias.TabIndex = 43;
            this.categoriaGanancias.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.categoriaGanancias.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.categoriaGanancias.TextMarginLeft = 0;
            this.categoriaGanancias.TextPadding = new System.Windows.Forms.Padding(0);
            this.categoriaGanancias.UseDefaultRadiusAndThickness = true;
            this.categoriaGanancias.Click += new System.EventHandler(this.categoriaGanancias_Click);
            // 
            // Compras
            // 
            this.Compras.AllowAnimations = true;
            this.Compras.AllowMouseEffects = true;
            this.Compras.AllowToggling = false;
            this.Compras.AnimationSpeed = 200;
            this.Compras.AutoGenerateColors = false;
            this.Compras.AutoRoundBorders = true;
            this.Compras.AutoSizeLeftIcon = true;
            this.Compras.AutoSizeRightIcon = true;
            this.Compras.BackColor = System.Drawing.Color.Transparent;
            this.Compras.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.Compras.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("Compras.BackgroundImage")));
            this.Compras.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.Compras.ButtonText = "Compras";
            this.Compras.ButtonTextMarginLeft = 0;
            this.Compras.ColorContrastOnClick = 45;
            this.Compras.ColorContrastOnHover = 45;
            this.Compras.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.Compras.CustomizableEdges = borderEdges2;
            this.Compras.DialogResult = System.Windows.Forms.DialogResult.None;
            this.Compras.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.Compras.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.Compras.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.Compras.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.Compras.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.Compras.ForeColor = System.Drawing.Color.White;
            this.Compras.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.Compras.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.Compras.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.Compras.IconMarginLeft = 11;
            this.Compras.IconPadding = 10;
            this.Compras.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.Compras.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.Compras.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.Compras.IconSize = 25;
            this.Compras.IdleBorderColor = System.Drawing.Color.Black;
            this.Compras.IdleBorderRadius = 37;
            this.Compras.IdleBorderThickness = 1;
            this.Compras.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.Compras.IdleIconLeftImage = null;
            this.Compras.IdleIconRightImage = null;
            this.Compras.IndicateFocus = false;
            this.Compras.Location = new System.Drawing.Point(273, 169);
            this.Compras.Name = "Compras";
            this.Compras.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.Compras.OnDisabledState.BorderRadius = 1;
            this.Compras.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.Compras.OnDisabledState.BorderThickness = 1;
            this.Compras.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.Compras.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.Compras.OnDisabledState.IconLeftImage = null;
            this.Compras.OnDisabledState.IconRightImage = null;
            this.Compras.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.Compras.onHoverState.BorderRadius = 1;
            this.Compras.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.Compras.onHoverState.BorderThickness = 1;
            this.Compras.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.Compras.onHoverState.ForeColor = System.Drawing.Color.White;
            this.Compras.onHoverState.IconLeftImage = null;
            this.Compras.onHoverState.IconRightImage = null;
            this.Compras.OnIdleState.BorderColor = System.Drawing.Color.Black;
            this.Compras.OnIdleState.BorderRadius = 1;
            this.Compras.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.Compras.OnIdleState.BorderThickness = 1;
            this.Compras.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.Compras.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.Compras.OnIdleState.IconLeftImage = null;
            this.Compras.OnIdleState.IconRightImage = null;
            this.Compras.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.Compras.OnPressedState.BorderRadius = 1;
            this.Compras.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.Compras.OnPressedState.BorderThickness = 1;
            this.Compras.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.Compras.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.Compras.OnPressedState.IconLeftImage = null;
            this.Compras.OnPressedState.IconRightImage = null;
            this.Compras.Size = new System.Drawing.Size(150, 39);
            this.Compras.TabIndex = 44;
            this.Compras.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.Compras.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.Compras.TextMarginLeft = 0;
            this.Compras.TextPadding = new System.Windows.Forms.Padding(0);
            this.Compras.UseDefaultRadiusAndThickness = true;
            this.Compras.Click += new System.EventHandler(this.bunifuButton22_Click);
            // 
            // Ventas
            // 
            this.Ventas.AllowAnimations = true;
            this.Ventas.AllowMouseEffects = true;
            this.Ventas.AllowToggling = false;
            this.Ventas.AnimationSpeed = 200;
            this.Ventas.AutoGenerateColors = false;
            this.Ventas.AutoRoundBorders = true;
            this.Ventas.AutoSizeLeftIcon = true;
            this.Ventas.AutoSizeRightIcon = true;
            this.Ventas.BackColor = System.Drawing.Color.Transparent;
            this.Ventas.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.Ventas.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("Ventas.BackgroundImage")));
            this.Ventas.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.Ventas.ButtonText = "Ventas";
            this.Ventas.ButtonTextMarginLeft = 0;
            this.Ventas.ColorContrastOnClick = 45;
            this.Ventas.ColorContrastOnHover = 45;
            this.Ventas.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.Ventas.CustomizableEdges = borderEdges3;
            this.Ventas.DialogResult = System.Windows.Forms.DialogResult.None;
            this.Ventas.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.Ventas.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.Ventas.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.Ventas.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.Ventas.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.Ventas.ForeColor = System.Drawing.Color.White;
            this.Ventas.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.Ventas.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.Ventas.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.Ventas.IconMarginLeft = 11;
            this.Ventas.IconPadding = 10;
            this.Ventas.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.Ventas.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.Ventas.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.Ventas.IconSize = 25;
            this.Ventas.IdleBorderColor = System.Drawing.Color.Black;
            this.Ventas.IdleBorderRadius = 37;
            this.Ventas.IdleBorderThickness = 1;
            this.Ventas.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.Ventas.IdleIconLeftImage = null;
            this.Ventas.IdleIconRightImage = null;
            this.Ventas.IndicateFocus = false;
            this.Ventas.Location = new System.Drawing.Point(435, 170);
            this.Ventas.Name = "Ventas";
            this.Ventas.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.Ventas.OnDisabledState.BorderRadius = 1;
            this.Ventas.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.Ventas.OnDisabledState.BorderThickness = 1;
            this.Ventas.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.Ventas.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.Ventas.OnDisabledState.IconLeftImage = null;
            this.Ventas.OnDisabledState.IconRightImage = null;
            this.Ventas.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.Ventas.onHoverState.BorderRadius = 1;
            this.Ventas.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.Ventas.onHoverState.BorderThickness = 1;
            this.Ventas.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.Ventas.onHoverState.ForeColor = System.Drawing.Color.White;
            this.Ventas.onHoverState.IconLeftImage = null;
            this.Ventas.onHoverState.IconRightImage = null;
            this.Ventas.OnIdleState.BorderColor = System.Drawing.Color.Black;
            this.Ventas.OnIdleState.BorderRadius = 1;
            this.Ventas.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.Ventas.OnIdleState.BorderThickness = 1;
            this.Ventas.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.Ventas.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.Ventas.OnIdleState.IconLeftImage = null;
            this.Ventas.OnIdleState.IconRightImage = null;
            this.Ventas.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.Ventas.OnPressedState.BorderRadius = 1;
            this.Ventas.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.Ventas.OnPressedState.BorderThickness = 1;
            this.Ventas.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.Ventas.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.Ventas.OnPressedState.IconLeftImage = null;
            this.Ventas.OnPressedState.IconRightImage = null;
            this.Ventas.Size = new System.Drawing.Size(150, 39);
            this.Ventas.TabIndex = 45;
            this.Ventas.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.Ventas.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.Ventas.TextMarginLeft = 0;
            this.Ventas.TextPadding = new System.Windows.Forms.Padding(0);
            this.Ventas.UseDefaultRadiusAndThickness = true;
            this.Ventas.Click += new System.EventHandler(this.Ventas_Click);
            // 
            // btnStock
            // 
            this.btnStock.AllowAnimations = true;
            this.btnStock.AllowMouseEffects = true;
            this.btnStock.AllowToggling = false;
            this.btnStock.AnimationSpeed = 200;
            this.btnStock.AutoGenerateColors = false;
            this.btnStock.AutoRoundBorders = true;
            this.btnStock.AutoSizeLeftIcon = true;
            this.btnStock.AutoSizeRightIcon = true;
            this.btnStock.BackColor = System.Drawing.Color.Transparent;
            this.btnStock.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.btnStock.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnStock.BackgroundImage")));
            this.btnStock.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnStock.ButtonText = "Stock";
            this.btnStock.ButtonTextMarginLeft = 0;
            this.btnStock.ColorContrastOnClick = 45;
            this.btnStock.ColorContrastOnHover = 45;
            this.btnStock.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            this.btnStock.CustomizableEdges = borderEdges4;
            this.btnStock.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnStock.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnStock.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnStock.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnStock.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.btnStock.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.btnStock.ForeColor = System.Drawing.Color.White;
            this.btnStock.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnStock.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.btnStock.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnStock.IconMarginLeft = 11;
            this.btnStock.IconPadding = 10;
            this.btnStock.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnStock.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.btnStock.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnStock.IconSize = 25;
            this.btnStock.IdleBorderColor = System.Drawing.Color.Black;
            this.btnStock.IdleBorderRadius = 37;
            this.btnStock.IdleBorderThickness = 1;
            this.btnStock.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.btnStock.IdleIconLeftImage = null;
            this.btnStock.IdleIconRightImage = null;
            this.btnStock.IndicateFocus = false;
            this.btnStock.Location = new System.Drawing.Point(357, 214);
            this.btnStock.Name = "btnStock";
            this.btnStock.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnStock.OnDisabledState.BorderRadius = 1;
            this.btnStock.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnStock.OnDisabledState.BorderThickness = 1;
            this.btnStock.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnStock.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnStock.OnDisabledState.IconLeftImage = null;
            this.btnStock.OnDisabledState.IconRightImage = null;
            this.btnStock.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnStock.onHoverState.BorderRadius = 1;
            this.btnStock.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnStock.onHoverState.BorderThickness = 1;
            this.btnStock.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnStock.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnStock.onHoverState.IconLeftImage = null;
            this.btnStock.onHoverState.IconRightImage = null;
            this.btnStock.OnIdleState.BorderColor = System.Drawing.Color.Black;
            this.btnStock.OnIdleState.BorderRadius = 1;
            this.btnStock.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnStock.OnIdleState.BorderThickness = 1;
            this.btnStock.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.btnStock.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnStock.OnIdleState.IconLeftImage = null;
            this.btnStock.OnIdleState.IconRightImage = null;
            this.btnStock.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnStock.OnPressedState.BorderRadius = 1;
            this.btnStock.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnStock.OnPressedState.BorderThickness = 1;
            this.btnStock.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnStock.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnStock.OnPressedState.IconLeftImage = null;
            this.btnStock.OnPressedState.IconRightImage = null;
            this.btnStock.Size = new System.Drawing.Size(150, 39);
            this.btnStock.TabIndex = 46;
            this.btnStock.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnStock.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnStock.TextMarginLeft = 0;
            this.btnStock.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnStock.UseDefaultRadiusAndThickness = true;
            this.btnStock.Click += new System.EventHandler(this.btnStock_Click);
            // 
            // gananciasVendedor
            // 
            this.gananciasVendedor.AllowAnimations = true;
            this.gananciasVendedor.AllowMouseEffects = true;
            this.gananciasVendedor.AllowToggling = false;
            this.gananciasVendedor.AnimationSpeed = 200;
            this.gananciasVendedor.AutoGenerateColors = false;
            this.gananciasVendedor.AutoRoundBorders = true;
            this.gananciasVendedor.AutoSizeLeftIcon = true;
            this.gananciasVendedor.AutoSizeRightIcon = true;
            this.gananciasVendedor.BackColor = System.Drawing.Color.Transparent;
            this.gananciasVendedor.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.gananciasVendedor.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("gananciasVendedor.BackgroundImage")));
            this.gananciasVendedor.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.gananciasVendedor.ButtonText = "Ganancias por Vendedor";
            this.gananciasVendedor.ButtonTextMarginLeft = 0;
            this.gananciasVendedor.ColorContrastOnClick = 45;
            this.gananciasVendedor.ColorContrastOnHover = 45;
            this.gananciasVendedor.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges5.BottomLeft = true;
            borderEdges5.BottomRight = true;
            borderEdges5.TopLeft = true;
            borderEdges5.TopRight = true;
            this.gananciasVendedor.CustomizableEdges = borderEdges5;
            this.gananciasVendedor.DialogResult = System.Windows.Forms.DialogResult.None;
            this.gananciasVendedor.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.gananciasVendedor.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.gananciasVendedor.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.gananciasVendedor.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.gananciasVendedor.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.gananciasVendedor.ForeColor = System.Drawing.Color.White;
            this.gananciasVendedor.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.gananciasVendedor.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.gananciasVendedor.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.gananciasVendedor.IconMarginLeft = 11;
            this.gananciasVendedor.IconPadding = 10;
            this.gananciasVendedor.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.gananciasVendedor.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.gananciasVendedor.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.gananciasVendedor.IconSize = 25;
            this.gananciasVendedor.IdleBorderColor = System.Drawing.Color.Black;
            this.gananciasVendedor.IdleBorderRadius = 37;
            this.gananciasVendedor.IdleBorderThickness = 1;
            this.gananciasVendedor.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.gananciasVendedor.IdleIconLeftImage = null;
            this.gananciasVendedor.IdleIconRightImage = null;
            this.gananciasVendedor.IndicateFocus = false;
            this.gananciasVendedor.Location = new System.Drawing.Point(601, 170);
            this.gananciasVendedor.Name = "gananciasVendedor";
            this.gananciasVendedor.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.gananciasVendedor.OnDisabledState.BorderRadius = 1;
            this.gananciasVendedor.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.gananciasVendedor.OnDisabledState.BorderThickness = 1;
            this.gananciasVendedor.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.gananciasVendedor.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.gananciasVendedor.OnDisabledState.IconLeftImage = null;
            this.gananciasVendedor.OnDisabledState.IconRightImage = null;
            this.gananciasVendedor.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.gananciasVendedor.onHoverState.BorderRadius = 1;
            this.gananciasVendedor.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.gananciasVendedor.onHoverState.BorderThickness = 1;
            this.gananciasVendedor.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.gananciasVendedor.onHoverState.ForeColor = System.Drawing.Color.White;
            this.gananciasVendedor.onHoverState.IconLeftImage = null;
            this.gananciasVendedor.onHoverState.IconRightImage = null;
            this.gananciasVendedor.OnIdleState.BorderColor = System.Drawing.Color.Black;
            this.gananciasVendedor.OnIdleState.BorderRadius = 1;
            this.gananciasVendedor.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.gananciasVendedor.OnIdleState.BorderThickness = 1;
            this.gananciasVendedor.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.gananciasVendedor.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.gananciasVendedor.OnIdleState.IconLeftImage = null;
            this.gananciasVendedor.OnIdleState.IconRightImage = null;
            this.gananciasVendedor.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.gananciasVendedor.OnPressedState.BorderRadius = 1;
            this.gananciasVendedor.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.gananciasVendedor.OnPressedState.BorderThickness = 1;
            this.gananciasVendedor.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.gananciasVendedor.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.gananciasVendedor.OnPressedState.IconLeftImage = null;
            this.gananciasVendedor.OnPressedState.IconRightImage = null;
            this.gananciasVendedor.Size = new System.Drawing.Size(150, 39);
            this.gananciasVendedor.TabIndex = 47;
            this.gananciasVendedor.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.gananciasVendedor.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.gananciasVendedor.TextMarginLeft = 0;
            this.gananciasVendedor.TextPadding = new System.Windows.Forms.Padding(0);
            this.gananciasVendedor.UseDefaultRadiusAndThickness = true;
            this.gananciasVendedor.Click += new System.EventHandler(this.gananciasVendedor_Click);
            // 
            // bunifuButton21
            // 
            this.bunifuButton21.AllowAnimations = true;
            this.bunifuButton21.AllowMouseEffects = true;
            this.bunifuButton21.AllowToggling = false;
            this.bunifuButton21.AnimationSpeed = 200;
            this.bunifuButton21.AutoGenerateColors = false;
            this.bunifuButton21.AutoRoundBorders = true;
            this.bunifuButton21.AutoSizeLeftIcon = true;
            this.bunifuButton21.AutoSizeRightIcon = true;
            this.bunifuButton21.BackColor = System.Drawing.Color.Transparent;
            this.bunifuButton21.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.bunifuButton21.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuButton21.BackgroundImage")));
            this.bunifuButton21.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButton21.ButtonText = "Ver mis ventas";
            this.bunifuButton21.ButtonTextMarginLeft = 0;
            this.bunifuButton21.ColorContrastOnClick = 45;
            this.bunifuButton21.ColorContrastOnHover = 45;
            this.bunifuButton21.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges6.BottomLeft = true;
            borderEdges6.BottomRight = true;
            borderEdges6.TopLeft = true;
            borderEdges6.TopRight = true;
            this.bunifuButton21.CustomizableEdges = borderEdges6;
            this.bunifuButton21.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuButton21.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton21.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton21.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton21.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.bunifuButton21.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.bunifuButton21.ForeColor = System.Drawing.Color.White;
            this.bunifuButton21.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bunifuButton21.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.bunifuButton21.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.bunifuButton21.IconMarginLeft = 11;
            this.bunifuButton21.IconPadding = 10;
            this.bunifuButton21.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bunifuButton21.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.bunifuButton21.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.bunifuButton21.IconSize = 25;
            this.bunifuButton21.IdleBorderColor = System.Drawing.Color.Black;
            this.bunifuButton21.IdleBorderRadius = 37;
            this.bunifuButton21.IdleBorderThickness = 1;
            this.bunifuButton21.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.bunifuButton21.IdleIconLeftImage = null;
            this.bunifuButton21.IdleIconRightImage = null;
            this.bunifuButton21.IndicateFocus = false;
            this.bunifuButton21.Location = new System.Drawing.Point(357, 259);
            this.bunifuButton21.Name = "bunifuButton21";
            this.bunifuButton21.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton21.OnDisabledState.BorderRadius = 1;
            this.bunifuButton21.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButton21.OnDisabledState.BorderThickness = 1;
            this.bunifuButton21.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton21.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton21.OnDisabledState.IconLeftImage = null;
            this.bunifuButton21.OnDisabledState.IconRightImage = null;
            this.bunifuButton21.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuButton21.onHoverState.BorderRadius = 1;
            this.bunifuButton21.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButton21.onHoverState.BorderThickness = 1;
            this.bunifuButton21.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuButton21.onHoverState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton21.onHoverState.IconLeftImage = null;
            this.bunifuButton21.onHoverState.IconRightImage = null;
            this.bunifuButton21.OnIdleState.BorderColor = System.Drawing.Color.Black;
            this.bunifuButton21.OnIdleState.BorderRadius = 1;
            this.bunifuButton21.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButton21.OnIdleState.BorderThickness = 1;
            this.bunifuButton21.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.bunifuButton21.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton21.OnIdleState.IconLeftImage = null;
            this.bunifuButton21.OnIdleState.IconRightImage = null;
            this.bunifuButton21.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButton21.OnPressedState.BorderRadius = 1;
            this.bunifuButton21.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButton21.OnPressedState.BorderThickness = 1;
            this.bunifuButton21.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButton21.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton21.OnPressedState.IconLeftImage = null;
            this.bunifuButton21.OnPressedState.IconRightImage = null;
            this.bunifuButton21.Size = new System.Drawing.Size(150, 39);
            this.bunifuButton21.TabIndex = 48;
            this.bunifuButton21.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.bunifuButton21.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bunifuButton21.TextMarginLeft = 0;
            this.bunifuButton21.TextPadding = new System.Windows.Forms.Padding(0);
            this.bunifuButton21.UseDefaultRadiusAndThickness = true;
            this.bunifuButton21.Click += new System.EventHandler(this.bunifuButton21_Click);
            // 
            // btnProductoMasVendido
            // 
            this.btnProductoMasVendido.AllowAnimations = true;
            this.btnProductoMasVendido.AllowMouseEffects = true;
            this.btnProductoMasVendido.AllowToggling = false;
            this.btnProductoMasVendido.AnimationSpeed = 200;
            this.btnProductoMasVendido.AutoGenerateColors = false;
            this.btnProductoMasVendido.AutoRoundBorders = true;
            this.btnProductoMasVendido.AutoSizeLeftIcon = true;
            this.btnProductoMasVendido.AutoSizeRightIcon = true;
            this.btnProductoMasVendido.BackColor = System.Drawing.Color.Transparent;
            this.btnProductoMasVendido.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.btnProductoMasVendido.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnProductoMasVendido.BackgroundImage")));
            this.btnProductoMasVendido.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnProductoMasVendido.ButtonText = "Productos mas vendidos";
            this.btnProductoMasVendido.ButtonTextMarginLeft = 0;
            this.btnProductoMasVendido.ColorContrastOnClick = 45;
            this.btnProductoMasVendido.ColorContrastOnHover = 45;
            this.btnProductoMasVendido.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges7.BottomLeft = true;
            borderEdges7.BottomRight = true;
            borderEdges7.TopLeft = true;
            borderEdges7.TopRight = true;
            this.btnProductoMasVendido.CustomizableEdges = borderEdges7;
            this.btnProductoMasVendido.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnProductoMasVendido.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnProductoMasVendido.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnProductoMasVendido.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnProductoMasVendido.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.btnProductoMasVendido.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.btnProductoMasVendido.ForeColor = System.Drawing.Color.White;
            this.btnProductoMasVendido.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnProductoMasVendido.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.btnProductoMasVendido.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnProductoMasVendido.IconMarginLeft = 11;
            this.btnProductoMasVendido.IconPadding = 10;
            this.btnProductoMasVendido.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnProductoMasVendido.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.btnProductoMasVendido.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnProductoMasVendido.IconSize = 25;
            this.btnProductoMasVendido.IdleBorderColor = System.Drawing.Color.Black;
            this.btnProductoMasVendido.IdleBorderRadius = 37;
            this.btnProductoMasVendido.IdleBorderThickness = 1;
            this.btnProductoMasVendido.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.btnProductoMasVendido.IdleIconLeftImage = null;
            this.btnProductoMasVendido.IdleIconRightImage = null;
            this.btnProductoMasVendido.IndicateFocus = false;
            this.btnProductoMasVendido.Location = new System.Drawing.Point(188, 215);
            this.btnProductoMasVendido.Name = "btnProductoMasVendido";
            this.btnProductoMasVendido.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnProductoMasVendido.OnDisabledState.BorderRadius = 1;
            this.btnProductoMasVendido.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnProductoMasVendido.OnDisabledState.BorderThickness = 1;
            this.btnProductoMasVendido.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnProductoMasVendido.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnProductoMasVendido.OnDisabledState.IconLeftImage = null;
            this.btnProductoMasVendido.OnDisabledState.IconRightImage = null;
            this.btnProductoMasVendido.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnProductoMasVendido.onHoverState.BorderRadius = 1;
            this.btnProductoMasVendido.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnProductoMasVendido.onHoverState.BorderThickness = 1;
            this.btnProductoMasVendido.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnProductoMasVendido.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnProductoMasVendido.onHoverState.IconLeftImage = null;
            this.btnProductoMasVendido.onHoverState.IconRightImage = null;
            this.btnProductoMasVendido.OnIdleState.BorderColor = System.Drawing.Color.Black;
            this.btnProductoMasVendido.OnIdleState.BorderRadius = 1;
            this.btnProductoMasVendido.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnProductoMasVendido.OnIdleState.BorderThickness = 1;
            this.btnProductoMasVendido.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.btnProductoMasVendido.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnProductoMasVendido.OnIdleState.IconLeftImage = null;
            this.btnProductoMasVendido.OnIdleState.IconRightImage = null;
            this.btnProductoMasVendido.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnProductoMasVendido.OnPressedState.BorderRadius = 1;
            this.btnProductoMasVendido.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnProductoMasVendido.OnPressedState.BorderThickness = 1;
            this.btnProductoMasVendido.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnProductoMasVendido.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnProductoMasVendido.OnPressedState.IconLeftImage = null;
            this.btnProductoMasVendido.OnPressedState.IconRightImage = null;
            this.btnProductoMasVendido.Size = new System.Drawing.Size(150, 39);
            this.btnProductoMasVendido.TabIndex = 49;
            this.btnProductoMasVendido.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnProductoMasVendido.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnProductoMasVendido.TextMarginLeft = 0;
            this.btnProductoMasVendido.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnProductoMasVendido.UseDefaultRadiusAndThickness = true;
            this.btnProductoMasVendido.Click += new System.EventHandler(this.btnProductoMasVendido_Click);
            // 
            // bunifuButton22
            // 
            this.bunifuButton22.AllowAnimations = true;
            this.bunifuButton22.AllowMouseEffects = true;
            this.bunifuButton22.AllowToggling = false;
            this.bunifuButton22.AnimationSpeed = 200;
            this.bunifuButton22.AutoGenerateColors = false;
            this.bunifuButton22.AutoRoundBorders = true;
            this.bunifuButton22.AutoSizeLeftIcon = true;
            this.bunifuButton22.AutoSizeRightIcon = true;
            this.bunifuButton22.BackColor = System.Drawing.Color.Transparent;
            this.bunifuButton22.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.bunifuButton22.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuButton22.BackgroundImage")));
            this.bunifuButton22.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButton22.ButtonText = "Categorias mas vendidas";
            this.bunifuButton22.ButtonTextMarginLeft = 0;
            this.bunifuButton22.ColorContrastOnClick = 45;
            this.bunifuButton22.ColorContrastOnHover = 45;
            this.bunifuButton22.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges8.BottomLeft = true;
            borderEdges8.BottomRight = true;
            borderEdges8.TopLeft = true;
            borderEdges8.TopRight = true;
            this.bunifuButton22.CustomizableEdges = borderEdges8;
            this.bunifuButton22.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuButton22.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton22.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton22.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton22.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.bunifuButton22.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.bunifuButton22.ForeColor = System.Drawing.Color.White;
            this.bunifuButton22.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bunifuButton22.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.bunifuButton22.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.bunifuButton22.IconMarginLeft = 11;
            this.bunifuButton22.IconPadding = 10;
            this.bunifuButton22.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bunifuButton22.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.bunifuButton22.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.bunifuButton22.IconSize = 25;
            this.bunifuButton22.IdleBorderColor = System.Drawing.Color.Black;
            this.bunifuButton22.IdleBorderRadius = 37;
            this.bunifuButton22.IdleBorderThickness = 1;
            this.bunifuButton22.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.bunifuButton22.IdleIconLeftImage = null;
            this.bunifuButton22.IdleIconRightImage = null;
            this.bunifuButton22.IndicateFocus = false;
            this.bunifuButton22.Location = new System.Drawing.Point(534, 215);
            this.bunifuButton22.Name = "bunifuButton22";
            this.bunifuButton22.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton22.OnDisabledState.BorderRadius = 1;
            this.bunifuButton22.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButton22.OnDisabledState.BorderThickness = 1;
            this.bunifuButton22.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton22.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton22.OnDisabledState.IconLeftImage = null;
            this.bunifuButton22.OnDisabledState.IconRightImage = null;
            this.bunifuButton22.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuButton22.onHoverState.BorderRadius = 1;
            this.bunifuButton22.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButton22.onHoverState.BorderThickness = 1;
            this.bunifuButton22.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuButton22.onHoverState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton22.onHoverState.IconLeftImage = null;
            this.bunifuButton22.onHoverState.IconRightImage = null;
            this.bunifuButton22.OnIdleState.BorderColor = System.Drawing.Color.Black;
            this.bunifuButton22.OnIdleState.BorderRadius = 1;
            this.bunifuButton22.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButton22.OnIdleState.BorderThickness = 1;
            this.bunifuButton22.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.bunifuButton22.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton22.OnIdleState.IconLeftImage = null;
            this.bunifuButton22.OnIdleState.IconRightImage = null;
            this.bunifuButton22.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButton22.OnPressedState.BorderRadius = 1;
            this.bunifuButton22.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButton22.OnPressedState.BorderThickness = 1;
            this.bunifuButton22.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButton22.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton22.OnPressedState.IconLeftImage = null;
            this.bunifuButton22.OnPressedState.IconRightImage = null;
            this.bunifuButton22.Size = new System.Drawing.Size(150, 39);
            this.bunifuButton22.TabIndex = 50;
            this.bunifuButton22.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.bunifuButton22.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bunifuButton22.TextMarginLeft = 0;
            this.bunifuButton22.TextPadding = new System.Windows.Forms.Padding(0);
            this.bunifuButton22.UseDefaultRadiusAndThickness = true;
            this.bunifuButton22.Click += new System.EventHandler(this.bunifuButton22_Click_1);
            // 
            // ResumenFinanciero
            // 
            this.ResumenFinanciero.AllowAnimations = true;
            this.ResumenFinanciero.AllowMouseEffects = true;
            this.ResumenFinanciero.AllowToggling = false;
            this.ResumenFinanciero.AnimationSpeed = 200;
            this.ResumenFinanciero.AutoGenerateColors = false;
            this.ResumenFinanciero.AutoRoundBorders = true;
            this.ResumenFinanciero.AutoSizeLeftIcon = true;
            this.ResumenFinanciero.AutoSizeRightIcon = true;
            this.ResumenFinanciero.BackColor = System.Drawing.Color.Transparent;
            this.ResumenFinanciero.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.ResumenFinanciero.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("ResumenFinanciero.BackgroundImage")));
            this.ResumenFinanciero.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.ResumenFinanciero.ButtonText = "Resumen financiero";
            this.ResumenFinanciero.ButtonTextMarginLeft = 0;
            this.ResumenFinanciero.ColorContrastOnClick = 45;
            this.ResumenFinanciero.ColorContrastOnHover = 45;
            this.ResumenFinanciero.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges9.BottomLeft = true;
            borderEdges9.BottomRight = true;
            borderEdges9.TopLeft = true;
            borderEdges9.TopRight = true;
            this.ResumenFinanciero.CustomizableEdges = borderEdges9;
            this.ResumenFinanciero.DialogResult = System.Windows.Forms.DialogResult.None;
            this.ResumenFinanciero.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.ResumenFinanciero.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.ResumenFinanciero.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.ResumenFinanciero.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.ResumenFinanciero.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.ResumenFinanciero.ForeColor = System.Drawing.Color.White;
            this.ResumenFinanciero.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.ResumenFinanciero.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.ResumenFinanciero.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.ResumenFinanciero.IconMarginLeft = 11;
            this.ResumenFinanciero.IconPadding = 10;
            this.ResumenFinanciero.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.ResumenFinanciero.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.ResumenFinanciero.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.ResumenFinanciero.IconSize = 25;
            this.ResumenFinanciero.IdleBorderColor = System.Drawing.Color.Black;
            this.ResumenFinanciero.IdleBorderRadius = 37;
            this.ResumenFinanciero.IdleBorderThickness = 1;
            this.ResumenFinanciero.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.ResumenFinanciero.IdleIconLeftImage = null;
            this.ResumenFinanciero.IdleIconRightImage = null;
            this.ResumenFinanciero.IndicateFocus = false;
            this.ResumenFinanciero.Location = new System.Drawing.Point(357, 304);
            this.ResumenFinanciero.Name = "ResumenFinanciero";
            this.ResumenFinanciero.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.ResumenFinanciero.OnDisabledState.BorderRadius = 1;
            this.ResumenFinanciero.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.ResumenFinanciero.OnDisabledState.BorderThickness = 1;
            this.ResumenFinanciero.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.ResumenFinanciero.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.ResumenFinanciero.OnDisabledState.IconLeftImage = null;
            this.ResumenFinanciero.OnDisabledState.IconRightImage = null;
            this.ResumenFinanciero.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.ResumenFinanciero.onHoverState.BorderRadius = 1;
            this.ResumenFinanciero.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.ResumenFinanciero.onHoverState.BorderThickness = 1;
            this.ResumenFinanciero.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.ResumenFinanciero.onHoverState.ForeColor = System.Drawing.Color.White;
            this.ResumenFinanciero.onHoverState.IconLeftImage = null;
            this.ResumenFinanciero.onHoverState.IconRightImage = null;
            this.ResumenFinanciero.OnIdleState.BorderColor = System.Drawing.Color.Black;
            this.ResumenFinanciero.OnIdleState.BorderRadius = 1;
            this.ResumenFinanciero.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.ResumenFinanciero.OnIdleState.BorderThickness = 1;
            this.ResumenFinanciero.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.ResumenFinanciero.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.ResumenFinanciero.OnIdleState.IconLeftImage = null;
            this.ResumenFinanciero.OnIdleState.IconRightImage = null;
            this.ResumenFinanciero.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.ResumenFinanciero.OnPressedState.BorderRadius = 1;
            this.ResumenFinanciero.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.ResumenFinanciero.OnPressedState.BorderThickness = 1;
            this.ResumenFinanciero.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.ResumenFinanciero.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.ResumenFinanciero.OnPressedState.IconLeftImage = null;
            this.ResumenFinanciero.OnPressedState.IconRightImage = null;
            this.ResumenFinanciero.Size = new System.Drawing.Size(150, 39);
            this.ResumenFinanciero.TabIndex = 51;
            this.ResumenFinanciero.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.ResumenFinanciero.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.ResumenFinanciero.TextMarginLeft = 0;
            this.ResumenFinanciero.TextPadding = new System.Windows.Forms.Padding(0);
            this.ResumenFinanciero.UseDefaultRadiusAndThickness = true;
            this.ResumenFinanciero.Click += new System.EventHandler(this.ResumenFinanciero_Click);
            // 
            // frmReportes
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(889, 525);
            this.Controls.Add(this.ResumenFinanciero);
            this.Controls.Add(this.bunifuButton22);
            this.Controls.Add(this.btnProductoMasVendido);
            this.Controls.Add(this.bunifuButton21);
            this.Controls.Add(this.gananciasVendedor);
            this.Controls.Add(this.btnStock);
            this.Controls.Add(this.Ventas);
            this.Controls.Add(this.Compras);
            this.Controls.Add(this.categoriaGanancias);
            this.Controls.Add(this.bunifuLabel3);
            this.Controls.Add(this.bunifuLabel1);
            this.Name = "frmReportes";
            this.Text = "frmReportes";
            this.Load += new System.EventHandler(this.frmReportes_Load);
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel1;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel3;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 categoriaGanancias;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 Compras;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 Ventas;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 btnStock;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 gananciasVendedor;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 bunifuButton21;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 btnProductoMasVendido;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 bunifuButton22;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 ResumenFinanciero;
    }
}